### ISSUE TITLE
Sequential boxes : don't store absolute URLs for images

### ISSUE THREAD

**Issue by jvelo** [46cl/wp-boilerplate#1]
This will make it painful should we want to make sites both HTTP and HTTPS

We should either store relative URLS or better their ID with an automatic way to transform them in URLs when loaded.

**Comment by nesk** [comment]
The goal in the future is to store the image ID and nothing more. Storing a JSON object was a bad idea.

**Comment by jvelo** [comment]
Great. I agree.
