### ISSUE TITLE
Add a command to import the database and images of a remote project

### ISSUE THREAD

**Issue by nesk** [46cl/wp-boilerplate#16]
This should be done through SSH and the `wp-project.json` would contain the endpoint:

``` js
{
    // ...

    "remote-endpoint": "user@remote-server:/path/to/the/public/directory/"

    // ...
}
```

**Comment by nesk** [comment]
@jvelo I've added you as the current assignee since we need some server configuration before working on the client solution.

**Comment by jvelo** [comment]
OK
