### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by nesk** [46cl/wp-boilerplate#34]
What about MIT license @jvelo?

**Comment by jvelo** [comment]
I'm not a lawyer ; some seem to believe plugins & themes are derivative of WordPress code and would advise choosing the GPL or GPL compatible license to be compliant with WordPress license (see https://wordpress.org/news/2009/07/themes-are-gpl-too/ which is for themes but would apply for plugins as well I believe).
There is still debate whether this conclusion is correct or not ; but I'd rather err on the safe side and go with GPL.

**Comment by jvelo** [comment]
Interestingly, Timber has changed from GPL to MIT at some point : https://github.com/jarednova/timber/commit/d1a781cdcdd81aebd33e094eb3e0a5ed27a4431c

**Comment by jvelo** [comment]
Actually, the MIT is compatible with GPL, so let's go for it.

**Comment by nesk** [comment]
Since [theme](https://codex.wordpress.org/Theme_Development#Theme_Stylesheet) and [plugin](https://developer.wordpress.org/plugins/the-basics/header-requirements/) configurations allow to specify any other license than GPLv2, I don't think Wordpress requires us to use the same license as them.

However, [as stated in Wordpress' guidelines](https://wordpress.org/plugins/about/guidelines/), the license of the theme/plugin should be compatible with the GPLv2.
